### ISSUE TITLE
Change Employee->companies_employee_id

### ISSUE THREAD

**Issue by b2simms** [SWE4040Project/SchedulerSWE4040#18]
The `companies_employee_id` is set to an `int`

It makes more sense to change it to a `varchar2`

**Comment by JoshNorthrup** [comment]
He's the SQL to change the type to varchar and maintains the data already present

> alter table	employees
	add (temp_name varchar2(40));
update employees
	set temp_name = companies_employee_id;
alter table employees
	drop column companies_employee_id;
alter table employees
	rename column temp_name to companies_employee_id;

**Comment by JoshNorthrup** [comment]
java changes are on `admin-web`

**Comment by b2simms** [comment]
Changed.
