### ISSUE TITLE
duplicate cookies

### ISSUE THREAD

**Issue by JoshNorthrup** [SWE4040Project/SchedulerSWE4040#20]
I haven't figured out how to reproduce this yet, I just wanted to document it so I didn't forget. I ran into an issue where I had 2 Auth and 2 xsrfToken(I think this was the second) client side and couldn't log in. Presumably the expired tokens were being held on to and the new ones deleted when I revisited `/login`.

Accounting for multiple token in `logic.js` could fix the issue but there might be a better way to approach managing the cookies.

**Comment by b2simms** [comment]
Potentially related to altering the parameters when setting the cookies: http://stackoverflow.com/questions/5621775/cookie-is-set-twice-how-to-remove-the-duplicate

1. Changed the `path` variable
2. Changed the `expires` variable

**Comment by JoshNorthrup** [comment]
wasn't really an issue
